<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Timezone;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
		$data = [
			[ 'country_code' => null,'name' => 'UTC','city' => 'UTC','offset' => '0','gmt' => '+00:00','abbreviation' => 'UTC' ],
			[ 'country_code' => 'AD','name' => 'Europe/Andorra','city' => 'Andorra','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'AE','name' => 'Asia/Dubai','city' => 'Dubai','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'AF','name' => 'Asia/Kabul','city' => 'Kabul','offset' => '16200','gmt' => '+04:30','abbreviation' => '+0430' ],
			[ 'country_code' => 'AG','name' => 'America/Antigua','city' => 'Antigua','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'AI','name' => 'America/Anguilla','city' => 'Anguilla','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'AL','name' => 'Europe/Tirane','city' => 'Tirane','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'AM','name' => 'Asia/Yerevan','city' => 'Yerevan','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'AO','name' => 'Africa/Luanda','city' => 'Luanda','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/McMurdo','city' => 'McMurdo','offset' => '46800','gmt' => '+13:00','abbreviation' => 'NZDT' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Casey','city' => 'Casey','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Davis','city' => 'Davis','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/DumontDUrville','city' => 'DumontDUrville','offset' => '36000','gmt' => '+10:00','abbreviation' => '+10' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Mawson','city' => 'Mawson','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Palmer','city' => 'Palmer','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Rothera','city' => 'Rothera','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Syowa','city' => 'Syowa','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Troll','city' => 'Troll','offset' => '7200','gmt' => '+02:00','abbreviation' => '+02' ],
			[ 'country_code' => 'AQ','name' => 'Antarctica/Vostok','city' => 'Vostok','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Buenos_Aires','city' => 'Buenos Aires','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Cordoba','city' => 'Cordoba','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Salta','city' => 'Salta','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Jujuy','city' => 'Jujuy','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Tucuman','city' => 'Tucuman','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Catamarca','city' => 'Catamarca','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/La_Rioja','city' => 'La Rioja','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/San_Juan','city' => 'San Juan','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Mendoza','city' => 'Mendoza','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/San_Luis','city' => 'San Luis','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Rio_Gallegos','city' => 'Rio Gallegos','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AR','name' => 'America/Argentina/Ushuaia','city' => 'Ushuaia','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'AS','name' => 'Pacific/Pago_Pago','city' => 'Pago Pago','offset' => '-39600','gmt' => '-11:00','abbreviation' => 'SST' ],
			[ 'country_code' => 'AT','name' => 'Europe/Vienna','city' => 'Vienna','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'AU','name' => 'Australia/Lord_Howe','city' => 'Lord Howe','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'AU','name' => 'Antarctica/Macquarie','city' => 'Macquarie','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'AU','name' => 'Australia/Hobart','city' => 'Hobart','offset' => '39600','gmt' => '+11:00','abbreviation' => 'AEDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Currie','city' => 'Currie','offset' => '39600','gmt' => '+11:00','abbreviation' => 'AEDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Melbourne','city' => 'Melbourne','offset' => '39600','gmt' => '+11:00','abbreviation' => 'AEDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Sydney','city' => 'Sydney','offset' => '39600','gmt' => '+11:00','abbreviation' => 'AEDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Broken_Hill','city' => 'Broken Hill','offset' => '37800','gmt' => '+10:30','abbreviation' => 'ACDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Brisbane','city' => 'Brisbane','offset' => '36000','gmt' => '+10:00','abbreviation' => 'AEST' ],
			[ 'country_code' => 'AU','name' => 'Australia/Lindeman','city' => 'Lindeman','offset' => '36000','gmt' => '+10:00','abbreviation' => 'AEST' ],
			[ 'country_code' => 'AU','name' => 'Australia/Adelaide','city' => 'Adelaide','offset' => '37800','gmt' => '+10:30','abbreviation' => 'ACDT' ],
			[ 'country_code' => 'AU','name' => 'Australia/Darwin','city' => 'Darwin','offset' => '34200','gmt' => '+09:30','abbreviation' => 'ACST' ],
			[ 'country_code' => 'AU','name' => 'Australia/Perth','city' => 'Perth','offset' => '28800','gmt' => '+08:00','abbreviation' => 'AWST' ],
			[ 'country_code' => 'AU','name' => 'Australia/Eucla','city' => 'Eucla','offset' => '31500','gmt' => '+08:45','abbreviation' => '+0845' ],
			[ 'country_code' => 'AW','name' => 'America/Aruba','city' => 'Aruba','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'AX','name' => 'Europe/Mariehamn','city' => 'Mariehamn','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'AZ','name' => 'Asia/Baku','city' => 'Baku','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'BA','name' => 'Europe/Sarajevo','city' => 'Sarajevo','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'BB','name' => 'America/Barbados','city' => 'Barbados','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'BD','name' => 'Asia/Dhaka','city' => 'Dhaka','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'BE','name' => 'Europe/Brussels','city' => 'Brussels','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'BF','name' => 'Africa/Ouagadougou','city' => 'Ouagadougou','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'BG','name' => 'Europe/Sofia','city' => 'Sofia','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'BH','name' => 'Asia/Bahrain','city' => 'Bahrain','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'BI','name' => 'Africa/Bujumbura','city' => 'Bujumbura','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'BJ','name' => 'Africa/Porto-Novo','city' => 'Porto-Novo','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'BL','name' => 'America/St_Barthelemy','city' => 'St Barthelemy','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'BM','name' => 'Atlantic/Bermuda','city' => 'Bermuda','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'BN','name' => 'Asia/Brunei','city' => 'Brunei','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'BO','name' => 'America/La_Paz','city' => 'La Paz','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BQ','name' => 'America/Kralendijk','city' => 'Kralendijk','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'BR','name' => 'America/Noronha','city' => 'Noronha','offset' => '-7200','gmt' => '-02:00','abbreviation' => '-02' ],
			[ 'country_code' => 'BR','name' => 'America/Belem','city' => 'Belem','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Fortaleza','city' => 'Fortaleza','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Recife','city' => 'Recife','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Araguaina','city' => 'Araguaina','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Maceio','city' => 'Maceio','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Bahia','city' => 'Bahia','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Sao_Paulo','city' => 'Sao Paulo','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Campo_Grande','city' => 'Campo Grande','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BR','name' => 'America/Cuiaba','city' => 'Cuiaba','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BR','name' => 'America/Santarem','city' => 'Santarem','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'BR','name' => 'America/Porto_Velho','city' => 'Porto Velho','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BR','name' => 'America/Boa_Vista','city' => 'Boa Vista','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BR','name' => 'America/Manaus','city' => 'Manaus','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'BR','name' => 'America/Eirunepe','city' => 'Eirunepe','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'BR','name' => 'America/Rio_Branco','city' => 'Rio Branco','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'BS','name' => 'America/Nassau','city' => 'Nassau','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'BT','name' => 'Asia/Thimphu','city' => 'Thimphu','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'BW','name' => 'Africa/Gaborone','city' => 'Gaborone','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'BY','name' => 'Europe/Minsk','city' => 'Minsk','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'BZ','name' => 'America/Belize','city' => 'Belize','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'CA','name' => 'America/St_Johns','city' => 'St Johns','offset' => '-9000','gmt' => '-02:30','abbreviation' => 'NDT' ],
			[ 'country_code' => 'CA','name' => 'America/Halifax','city' => 'Halifax','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'CA','name' => 'America/Glace_Bay','city' => 'Glace Bay','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'CA','name' => 'America/Moncton','city' => 'Moncton','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'CA','name' => 'America/Goose_Bay','city' => 'Goose Bay','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'CA','name' => 'America/Blanc-Sablon','city' => 'Blanc-Sablon','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'CA','name' => 'America/Toronto','city' => 'Toronto','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'CA','name' => 'America/Nipigon','city' => 'Nipigon','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'CA','name' => 'America/Thunder_Bay','city' => 'Thunder Bay','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'CA','name' => 'America/Iqaluit','city' => 'Iqaluit','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'CA','name' => 'America/Pangnirtung','city' => 'Pangnirtung','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'CA','name' => 'America/Atikokan','city' => 'Atikokan','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'EST' ],
			[ 'country_code' => 'CA','name' => 'America/Winnipeg','city' => 'Winnipeg','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'CA','name' => 'America/Rainy_River','city' => 'Rainy River','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'CA','name' => 'America/Resolute','city' => 'Resolute','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'CA','name' => 'America/Rankin_Inlet','city' => 'Rankin Inlet','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'CA','name' => 'America/Regina','city' => 'Regina','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'CA','name' => 'America/Swift_Current','city' => 'Swift Current','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'CA','name' => 'America/Edmonton','city' => 'Edmonton','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'CA','name' => 'America/Cambridge_Bay','city' => 'Cambridge Bay','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'CA','name' => 'America/Yellowknife','city' => 'Yellowknife','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'CA','name' => 'America/Inuvik','city' => 'Inuvik','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'CA','name' => 'America/Creston','city' => 'Creston','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'MST' ],
			[ 'country_code' => 'CA','name' => 'America/Dawson_Creek','city' => 'Dawson Creek','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'MST' ],
			[ 'country_code' => 'CA','name' => 'America/Fort_Nelson','city' => 'Fort Nelson','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'MST' ],
			[ 'country_code' => 'CA','name' => 'America/Vancouver','city' => 'Vancouver','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'PDT' ],
			[ 'country_code' => 'CA','name' => 'America/Whitehorse','city' => 'Whitehorse','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'PDT' ],
			[ 'country_code' => 'CA','name' => 'America/Dawson','city' => 'Dawson','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'PDT' ],
			[ 'country_code' => 'CC','name' => 'Indian/Cocos','city' => 'Cocos','offset' => '23400','gmt' => '+06:30','abbreviation' => '+0630' ],
			[ 'country_code' => 'CD','name' => 'Africa/Kinshasa','city' => 'Kinshasa','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'CD','name' => 'Africa/Lubumbashi','city' => 'Lubumbashi','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'CF','name' => 'Africa/Bangui','city' => 'Bangui','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'CG','name' => 'Africa/Brazzaville','city' => 'Brazzaville','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'CH','name' => 'Europe/Zurich','city' => 'Zurich','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'CI','name' => 'Africa/Abidjan','city' => 'Abidjan','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'CK','name' => 'Pacific/Rarotonga','city' => 'Rarotonga','offset' => '-36000','gmt' => '-10:00','abbreviation' => '-10' ],
			[ 'country_code' => 'CL','name' => 'America/Santiago','city' => 'Santiago','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'CL','name' => 'America/Punta_Arenas','city' => 'Punta Arenas','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'CL','name' => 'Pacific/Easter','city' => 'Easter','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'CM','name' => 'Africa/Douala','city' => 'Douala','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'CN','name' => 'Asia/Shanghai','city' => 'Shanghai','offset' => '28800','gmt' => '+08:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'CN','name' => 'Asia/Urumqi','city' => 'Urumqi','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'CO','name' => 'America/Bogota','city' => 'Bogota','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'CR','name' => 'America/Costa_Rica','city' => 'Costa Rica','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'CU','name' => 'America/Havana','city' => 'Havana','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'CV','name' => 'Atlantic/Cape_Verde','city' => 'Cape Verde','offset' => '-3600','gmt' => '-01:00','abbreviation' => '-01' ],
			[ 'country_code' => 'CW','name' => 'America/Curacao','city' => 'Curacao','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'CX','name' => 'Indian/Christmas','city' => 'Christmas','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'CY','name' => 'Asia/Nicosia','city' => 'Nicosia','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'CY','name' => 'Asia/Famagusta','city' => 'Famagusta','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'CZ','name' => 'Europe/Prague','city' => 'Prague','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'DE','name' => 'Europe/Berlin','city' => 'Berlin','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'DE','name' => 'Europe/Busingen','city' => 'Busingen','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'DJ','name' => 'Africa/Djibouti','city' => 'Djibouti','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'DK','name' => 'Europe/Copenhagen','city' => 'Copenhagen','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'DM','name' => 'America/Dominica','city' => 'Dominica','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'DO','name' => 'America/Santo_Domingo','city' => 'Santo Domingo','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'DZ','name' => 'Africa/Algiers','city' => 'Algiers','offset' => '3600','gmt' => '+01:00','abbreviation' => 'CET' ],
			[ 'country_code' => 'EC','name' => 'America/Guayaquil','city' => 'Guayaquil','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'EC','name' => 'Pacific/Galapagos','city' => 'Galapagos','offset' => '-21600','gmt' => '-06:00','abbreviation' => '-06' ],
			[ 'country_code' => 'EE','name' => 'Europe/Tallinn','city' => 'Tallinn','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'EG','name' => 'Africa/Cairo','city' => 'Cairo','offset' => '7200','gmt' => '+02:00','abbreviation' => 'EET' ],
			[ 'country_code' => 'EH','name' => 'Africa/El_Aaiun','city' => 'El Aaiun','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'ER','name' => 'Africa/Asmara','city' => 'Asmara','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'ES','name' => 'Europe/Madrid','city' => 'Madrid','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'ES','name' => 'Africa/Ceuta','city' => 'Ceuta','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'ES','name' => 'Atlantic/Canary','city' => 'Canary','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'ET','name' => 'Africa/Addis_Ababa','city' => 'Addis Ababa','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'FI','name' => 'Europe/Helsinki','city' => 'Helsinki','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'FJ','name' => 'Pacific/Fiji','city' => 'Fiji','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'FK','name' => 'Atlantic/Stanley','city' => 'Stanley','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'FM','name' => 'Pacific/Chuuk','city' => 'Chuuk','offset' => '36000','gmt' => '+10:00','abbreviation' => '+10' ],
			[ 'country_code' => 'FM','name' => 'Pacific/Pohnpei','city' => 'Pohnpei','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'FM','name' => 'Pacific/Kosrae','city' => 'Kosrae','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'FO','name' => 'Atlantic/Faroe','city' => 'Faroe','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'FR','name' => 'Europe/Paris','city' => 'Paris','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'GA','name' => 'Africa/Libreville','city' => 'Libreville','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'GB','name' => 'Europe/London','city' => 'London','offset' => '3600','gmt' => '+01:00','abbreviation' => 'BST' ],
			[ 'country_code' => 'GD','name' => 'America/Grenada','city' => 'Grenada','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'GE','name' => 'Asia/Tbilisi','city' => 'Tbilisi','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'GF','name' => 'America/Cayenne','city' => 'Cayenne','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'GG','name' => 'Europe/Guernsey','city' => 'Guernsey','offset' => '3600','gmt' => '+01:00','abbreviation' => 'BST' ],
			[ 'country_code' => 'GH','name' => 'Africa/Accra','city' => 'Accra','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'GI','name' => 'Europe/Gibraltar','city' => 'Gibraltar','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'GL','name' => 'America/Godthab','city' => 'Godthab','offset' => '-7200','gmt' => '-02:00','abbreviation' => '-02' ],
			[ 'country_code' => 'GL','name' => 'America/Danmarkshavn','city' => 'Danmarkshavn','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'GL','name' => 'America/Scoresbysund','city' => 'Scoresbysund','offset' => '0','gmt' => '+00:00','abbreviation' => '+00' ],
			[ 'country_code' => 'GL','name' => 'America/Thule','city' => 'Thule','offset' => '-10800','gmt' => '-03:00','abbreviation' => 'ADT' ],
			[ 'country_code' => 'GM','name' => 'Africa/Banjul','city' => 'Banjul','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'GN','name' => 'Africa/Conakry','city' => 'Conakry','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'GP','name' => 'America/Guadeloupe','city' => 'Guadeloupe','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'GQ','name' => 'Africa/Malabo','city' => 'Malabo','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'GR','name' => 'Europe/Athens','city' => 'Athens','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'GS','name' => 'Atlantic/South_Georgia','city' => 'South Georgia','offset' => '-7200','gmt' => '-02:00','abbreviation' => '-02' ],
			[ 'country_code' => 'GT','name' => 'America/Guatemala','city' => 'Guatemala','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'GU','name' => 'Pacific/Guam','city' => 'Guam','offset' => '36000','gmt' => '+10:00','abbreviation' => 'ChST' ],
			[ 'country_code' => 'GW','name' => 'Africa/Bissau','city' => 'Bissau','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'GY','name' => 'America/Guyana','city' => 'Guyana','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'HK','name' => 'Asia/Hong_Kong','city' => 'Hong Kong','offset' => '28800','gmt' => '+08:00','abbreviation' => 'HKT' ],
			[ 'country_code' => 'HN','name' => 'America/Tegucigalpa','city' => 'Tegucigalpa','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'HR','name' => 'Europe/Zagreb','city' => 'Zagreb','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'HT','name' => 'America/Port-au-Prince','city' => 'Port-au-Prince','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'HU','name' => 'Europe/Budapest','city' => 'Budapest','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'ID','name' => 'Asia/Jakarta','city' => 'Jakarta','offset' => '25200','gmt' => '+07:00','abbreviation' => 'WIB' ],
			[ 'country_code' => 'ID','name' => 'Asia/Pontianak','city' => 'Pontianak','offset' => '25200','gmt' => '+07:00','abbreviation' => 'WIB' ],
			[ 'country_code' => 'ID','name' => 'Asia/Makassar','city' => 'Makassar','offset' => '28800','gmt' => '+08:00','abbreviation' => 'WITA' ],
			[ 'country_code' => 'ID','name' => 'Asia/Jayapura','city' => 'Jayapura','offset' => '32400','gmt' => '+09:00','abbreviation' => 'WIT' ],
			[ 'country_code' => 'IE','name' => 'Europe/Dublin','city' => 'Dublin','offset' => '3600','gmt' => '+01:00','abbreviation' => 'IST' ],
			[ 'country_code' => 'IL','name' => 'Asia/Jerusalem','city' => 'Jerusalem','offset' => '10800','gmt' => '+03:00','abbreviation' => 'IDT' ],
			[ 'country_code' => 'IM','name' => 'Europe/Isle_of_Man','city' => 'Isle of Man','offset' => '3600','gmt' => '+01:00','abbreviation' => 'BST' ],
			[ 'country_code' => 'IN','name' => 'Asia/Kolkata','city' => 'Kolkata','offset' => '19800','gmt' => '+05:30','abbreviation' => 'IST' ],
			[ 'country_code' => 'IO','name' => 'Indian/Chagos','city' => 'Chagos','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'IQ','name' => 'Asia/Baghdad','city' => 'Baghdad','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'IR','name' => 'Asia/Tehran','city' => 'Tehran','offset' => '12600','gmt' => '+03:30','abbreviation' => '+0330' ],
			[ 'country_code' => 'IS','name' => 'Atlantic/Reykjavik','city' => 'Reykjavik','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'IT','name' => 'Europe/Rome','city' => 'Rome','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'JE','name' => 'Europe/Jersey','city' => 'Jersey','offset' => '3600','gmt' => '+01:00','abbreviation' => 'BST' ],
			[ 'country_code' => 'JM','name' => 'America/Jamaica','city' => 'Jamaica','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'EST' ],
			[ 'country_code' => 'JO','name' => 'Asia/Amman','city' => 'Amman','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'JP','name' => 'Asia/Tokyo','city' => 'Tokyo','offset' => '32400','gmt' => '+09:00','abbreviation' => 'JST' ],
			[ 'country_code' => 'KE','name' => 'Africa/Nairobi','city' => 'Nairobi','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'KG','name' => 'Asia/Bishkek','city' => 'Bishkek','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'KH','name' => 'Asia/Phnom_Penh','city' => 'Phnom Penh','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'KI','name' => 'Pacific/Tarawa','city' => 'Tarawa','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'KI','name' => 'Pacific/Enderbury','city' => 'Enderbury','offset' => '46800','gmt' => '+13:00','abbreviation' => '+13' ],
			[ 'country_code' => 'KI','name' => 'Pacific/Kiritimati','city' => 'Kiritimati','offset' => '50400','gmt' => '+14:00','abbreviation' => '+14' ],
			[ 'country_code' => 'KM','name' => 'Indian/Comoro','city' => 'Comoro','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'KN','name' => 'America/St_Kitts','city' => 'St Kitts','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'KP','name' => 'Asia/Pyongyang','city' => 'Pyongyang','offset' => '30600','gmt' => '+08:30','abbreviation' => 'KST' ],
			[ 'country_code' => 'KR','name' => 'Asia/Seoul','city' => 'Seoul','offset' => '32400','gmt' => '+09:00','abbreviation' => 'KST' ],
			[ 'country_code' => 'KW','name' => 'Asia/Kuwait','city' => 'Kuwait','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'KY','name' => 'America/Cayman','city' => 'Cayman','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'EST' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Almaty','city' => 'Almaty','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Qyzylorda','city' => 'Qyzylorda','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Aqtobe','city' => 'Aqtobe','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Aqtau','city' => 'Aqtau','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Atyrau','city' => 'Atyrau','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'KZ','name' => 'Asia/Oral','city' => 'Oral','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'LA','name' => 'Asia/Vientiane','city' => 'Vientiane','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'LB','name' => 'Asia/Beirut','city' => 'Beirut','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'LC','name' => 'America/St_Lucia','city' => 'St Lucia','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'LI','name' => 'Europe/Vaduz','city' => 'Vaduz','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'LK','name' => 'Asia/Colombo','city' => 'Colombo','offset' => '19800','gmt' => '+05:30','abbreviation' => '+0530' ],
			[ 'country_code' => 'LR','name' => 'Africa/Monrovia','city' => 'Monrovia','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'LS','name' => 'Africa/Maseru','city' => 'Maseru','offset' => '7200','gmt' => '+02:00','abbreviation' => 'SAST' ],
			[ 'country_code' => 'LT','name' => 'Europe/Vilnius','city' => 'Vilnius','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'LU','name' => 'Europe/Luxembourg','city' => 'Luxembourg','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'LV','name' => 'Europe/Riga','city' => 'Riga','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'LY','name' => 'Africa/Tripoli','city' => 'Tripoli','offset' => '7200','gmt' => '+02:00','abbreviation' => 'EET' ],
			[ 'country_code' => 'MA','name' => 'Africa/Casablanca','city' => 'Casablanca','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'MC','name' => 'Europe/Monaco','city' => 'Monaco','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'MD','name' => 'Europe/Chisinau','city' => 'Chisinau','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'ME','name' => 'Europe/Podgorica','city' => 'Podgorica','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'MF','name' => 'America/Marigot','city' => 'Marigot','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'MG','name' => 'Indian/Antananarivo','city' => 'Antananarivo','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'MH','name' => 'Pacific/Majuro','city' => 'Majuro','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'MH','name' => 'Pacific/Kwajalein','city' => 'Kwajalein','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'MK','name' => 'Europe/Skopje','city' => 'Skopje','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'ML','name' => 'Africa/Bamako','city' => 'Bamako','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'MM','name' => 'Asia/Yangon','city' => 'Yangon','offset' => '23400','gmt' => '+06:30','abbreviation' => '+0630' ],
			[ 'country_code' => 'MN','name' => 'Asia/Ulaanbaatar','city' => 'Ulaanbaatar','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'MN','name' => 'Asia/Hovd','city' => 'Hovd','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'MN','name' => 'Asia/Choibalsan','city' => 'Choibalsan','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'MO','name' => 'Asia/Macau','city' => 'Macau','offset' => '28800','gmt' => '+08:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'MP','name' => 'Pacific/Saipan','city' => 'Saipan','offset' => '36000','gmt' => '+10:00','abbreviation' => 'ChST' ],
			[ 'country_code' => 'MQ','name' => 'America/Martinique','city' => 'Martinique','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'MR','name' => 'Africa/Nouakchott','city' => 'Nouakchott','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'MS','name' => 'America/Montserrat','city' => 'Montserrat','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'MT','name' => 'Europe/Malta','city' => 'Malta','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'MU','name' => 'Indian/Mauritius','city' => 'Mauritius','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'MV','name' => 'Indian/Maldives','city' => 'Maldives','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'MW','name' => 'Africa/Blantyre','city' => 'Blantyre','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'MX','name' => 'America/Mexico_City','city' => 'Mexico City','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'MX','name' => 'America/Cancun','city' => 'Cancun','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'EST' ],
			[ 'country_code' => 'MX','name' => 'America/Merida','city' => 'Merida','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'MX','name' => 'America/Monterrey','city' => 'Monterrey','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'MX','name' => 'America/Matamoros','city' => 'Matamoros','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'MX','name' => 'America/Mazatlan','city' => 'Mazatlan','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'MX','name' => 'America/Chihuahua','city' => 'Chihuahua','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'MX','name' => 'America/Ojinaga','city' => 'Ojinaga','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'MX','name' => 'America/Hermosillo','city' => 'Hermosillo','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'MST' ],
			[ 'country_code' => 'MX','name' => 'America/Tijuana','city' => 'Tijuana','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'PDT' ],
			[ 'country_code' => 'MX','name' => 'America/Bahia_Banderas','city' => 'Bahia Banderas','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'MY','name' => 'Asia/Kuala_Lumpur','city' => 'Kuala Lumpur','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'MY','name' => 'Asia/Kuching','city' => 'Kuching','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'MZ','name' => 'Africa/Maputo','city' => 'Maputo','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'NA','name' => 'Africa/Windhoek','city' => 'Windhoek','offset' => '7200','gmt' => '+02:00','abbreviation' => 'WAST' ],
			[ 'country_code' => 'NC','name' => 'Pacific/Noumea','city' => 'Noumea','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'NE','name' => 'Africa/Niamey','city' => 'Niamey','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'NF','name' => 'Pacific/Norfolk','city' => 'Norfolk','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'NG','name' => 'Africa/Lagos','city' => 'Lagos','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'NI','name' => 'America/Managua','city' => 'Managua','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'NL','name' => 'Europe/Amsterdam','city' => 'Amsterdam','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'NO','name' => 'Europe/Oslo','city' => 'Oslo','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'NP','name' => 'Asia/Kathmandu','city' => 'Kathmandu','offset' => '20700','gmt' => '+05:45','abbreviation' => '+0545' ],
			[ 'country_code' => 'NR','name' => 'Pacific/Nauru','city' => 'Nauru','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'NU','name' => 'Pacific/Niue','city' => 'Niue','offset' => '-39600','gmt' => '-11:00','abbreviation' => '-11' ],
			[ 'country_code' => 'NZ','name' => 'Pacific/Auckland','city' => 'Auckland','offset' => '46800','gmt' => '+13:00','abbreviation' => 'NZDT' ],
			[ 'country_code' => 'NZ','name' => 'Pacific/Chatham','city' => 'Chatham','offset' => '49500','gmt' => '+13:45','abbreviation' => '+1345' ],
			[ 'country_code' => 'OM','name' => 'Asia/Muscat','city' => 'Muscat','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'PA','name' => 'America/Panama','city' => 'Panama','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'EST' ],
			[ 'country_code' => 'PE','name' => 'America/Lima','city' => 'Lima','offset' => '-18000','gmt' => '-05:00','abbreviation' => '-05' ],
			[ 'country_code' => 'PF','name' => 'Pacific/Tahiti','city' => 'Tahiti','offset' => '-36000','gmt' => '-10:00','abbreviation' => '-10' ],
			[ 'country_code' => 'PF','name' => 'Pacific/Marquesas','city' => 'Marquesas','offset' => '-34200','gmt' => '-09:30','abbreviation' => '-0930' ],
			[ 'country_code' => 'PF','name' => 'Pacific/Gambier','city' => 'Gambier','offset' => '-32400','gmt' => '-09:00','abbreviation' => '-09' ],
			[ 'country_code' => 'PG','name' => 'Pacific/Port_Moresby','city' => 'Port Moresby','offset' => '36000','gmt' => '+10:00','abbreviation' => '+10' ],
			[ 'country_code' => 'PG','name' => 'Pacific/Bougainville','city' => 'Bougainville','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'PH','name' => 'Asia/Manila','city' => 'Manila','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'PK','name' => 'Asia/Karachi','city' => 'Karachi','offset' => '18000','gmt' => '+05:00','abbreviation' => 'PKT' ],
			[ 'country_code' => 'PL','name' => 'Europe/Warsaw','city' => 'Warsaw','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'PM','name' => 'America/Miquelon','city' => 'Miquelon','offset' => '-7200','gmt' => '-02:00','abbreviation' => '-02' ],
			[ 'country_code' => 'PN','name' => 'Pacific/Pitcairn','city' => 'Pitcairn','offset' => '-28800','gmt' => '-08:00','abbreviation' => '-08' ],
			[ 'country_code' => 'PR','name' => 'America/Puerto_Rico','city' => 'Puerto Rico','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'PS','name' => 'Asia/Gaza','city' => 'Gaza','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'PS','name' => 'Asia/Hebron','city' => 'Hebron','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'PT','name' => 'Europe/Lisbon','city' => 'Lisbon','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'PT','name' => 'Atlantic/Madeira','city' => 'Madeira','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WEST' ],
			[ 'country_code' => 'PT','name' => 'Atlantic/Azores','city' => 'Azores','offset' => '0','gmt' => '+00:00','abbreviation' => '+00' ],
			[ 'country_code' => 'PW','name' => 'Pacific/Palau','city' => 'Palau','offset' => '32400','gmt' => '+09:00','abbreviation' => '+09' ],
			[ 'country_code' => 'PY','name' => 'America/Asuncion','city' => 'Asuncion','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'QA','name' => 'Asia/Qatar','city' => 'Qatar','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'RE','name' => 'Indian/Reunion','city' => 'Reunion','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'RO','name' => 'Europe/Bucharest','city' => 'Bucharest','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'RS','name' => 'Europe/Belgrade','city' => 'Belgrade','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'RU','name' => 'Europe/Kaliningrad','city' => 'Kaliningrad','offset' => '7200','gmt' => '+02:00','abbreviation' => 'EET' ],
			[ 'country_code' => 'RU','name' => 'Europe/Moscow','city' => 'Moscow','offset' => '10800','gmt' => '+03:00','abbreviation' => 'MSK' ],
			[ 'country_code' => 'RU','name' => 'Europe/Simferopol','city' => 'Simferopol','offset' => '10800','gmt' => '+03:00','abbreviation' => 'MSK' ],
			[ 'country_code' => 'RU','name' => 'Europe/Volgograd','city' => 'Volgograd','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'RU','name' => 'Europe/Kirov','city' => 'Kirov','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'RU','name' => 'Europe/Astrakhan','city' => 'Astrakhan','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'RU','name' => 'Europe/Saratov','city' => 'Saratov','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'RU','name' => 'Europe/Ulyanovsk','city' => 'Ulyanovsk','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'RU','name' => 'Europe/Samara','city' => 'Samara','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'RU','name' => 'Asia/Yekaterinburg','city' => 'Yekaterinburg','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'RU','name' => 'Asia/Omsk','city' => 'Omsk','offset' => '21600','gmt' => '+06:00','abbreviation' => '+06' ],
			[ 'country_code' => 'RU','name' => 'Asia/Novosibirsk','city' => 'Novosibirsk','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'RU','name' => 'Asia/Barnaul','city' => 'Barnaul','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'RU','name' => 'Asia/Tomsk','city' => 'Tomsk','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'RU','name' => 'Asia/Novokuznetsk','city' => 'Novokuznetsk','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'RU','name' => 'Asia/Krasnoyarsk','city' => 'Krasnoyarsk','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'RU','name' => 'Asia/Irkutsk','city' => 'Irkutsk','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'RU','name' => 'Asia/Chita','city' => 'Chita','offset' => '32400','gmt' => '+09:00','abbreviation' => '+09' ],
			[ 'country_code' => 'RU','name' => 'Asia/Yakutsk','city' => 'Yakutsk','offset' => '32400','gmt' => '+09:00','abbreviation' => '+09' ],
			[ 'country_code' => 'RU','name' => 'Asia/Khandyga','city' => 'Khandyga','offset' => '32400','gmt' => '+09:00','abbreviation' => '+09' ],
			[ 'country_code' => 'RU','name' => 'Asia/Vladivostok','city' => 'Vladivostok','offset' => '36000','gmt' => '+10:00','abbreviation' => '+10' ],
			[ 'country_code' => 'RU','name' => 'Asia/Ust-Nera','city' => 'Ust-Nera','offset' => '36000','gmt' => '+10:00','abbreviation' => '+10' ],
			[ 'country_code' => 'RU','name' => 'Asia/Magadan','city' => 'Magadan','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'RU','name' => 'Asia/Sakhalin','city' => 'Sakhalin','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'RU','name' => 'Asia/Srednekolymsk','city' => 'Srednekolymsk','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'RU','name' => 'Asia/Kamchatka','city' => 'Kamchatka','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'RU','name' => 'Asia/Anadyr','city' => 'Anadyr','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'RW','name' => 'Africa/Kigali','city' => 'Kigali','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'SA','name' => 'Asia/Riyadh','city' => 'Riyadh','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'SB','name' => 'Pacific/Guadalcanal','city' => 'Guadalcanal','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'SC','name' => 'Indian/Mahe','city' => 'Mahe','offset' => '14400','gmt' => '+04:00','abbreviation' => '+04' ],
			[ 'country_code' => 'SD','name' => 'Africa/Khartoum','city' => 'Khartoum','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'SE','name' => 'Europe/Stockholm','city' => 'Stockholm','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'SG','name' => 'Asia/Singapore','city' => 'Singapore','offset' => '28800','gmt' => '+08:00','abbreviation' => '+08' ],
			[ 'country_code' => 'SH','name' => 'Atlantic/St_Helena','city' => 'St Helena','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'SI','name' => 'Europe/Ljubljana','city' => 'Ljubljana','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'SJ','name' => 'Arctic/Longyearbyen','city' => 'Longyearbyen','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'SK','name' => 'Europe/Bratislava','city' => 'Bratislava','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'SL','name' => 'Africa/Freetown','city' => 'Freetown','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'SM','name' => 'Europe/San_Marino','city' => 'San Marino','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'SN','name' => 'Africa/Dakar','city' => 'Dakar','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'SO','name' => 'Africa/Mogadishu','city' => 'Mogadishu','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'SR','name' => 'America/Paramaribo','city' => 'Paramaribo','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'SS','name' => 'Africa/Juba','city' => 'Juba','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'ST','name' => 'Africa/Sao_Tome','city' => 'Sao Tome','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'SV','name' => 'America/El_Salvador','city' => 'El Salvador','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'SX','name' => 'America/Lower_Princes','city' => 'Lower Princes','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'SY','name' => 'Asia/Damascus','city' => 'Damascus','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'SZ','name' => 'Africa/Mbabane','city' => 'Mbabane','offset' => '7200','gmt' => '+02:00','abbreviation' => 'SAST' ],
			[ 'country_code' => 'TC','name' => 'America/Grand_Turk','city' => 'Grand Turk','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'TD','name' => 'Africa/Ndjamena','city' => 'Ndjamena','offset' => '3600','gmt' => '+01:00','abbreviation' => 'WAT' ],
			[ 'country_code' => 'TF','name' => 'Indian/Kerguelen','city' => 'Kerguelen','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'TG','name' => 'Africa/Lome','city' => 'Lome','offset' => '0','gmt' => '+00:00','abbreviation' => 'GMT' ],
			[ 'country_code' => 'TH','name' => 'Asia/Bangkok','city' => 'Bangkok','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'TJ','name' => 'Asia/Dushanbe','city' => 'Dushanbe','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'TK','name' => 'Pacific/Fakaofo','city' => 'Fakaofo','offset' => '46800','gmt' => '+13:00','abbreviation' => '+13' ],
			[ 'country_code' => 'TL','name' => 'Asia/Dili','city' => 'Dili','offset' => '32400','gmt' => '+09:00','abbreviation' => '+09' ],
			[ 'country_code' => 'TM','name' => 'Asia/Ashgabat','city' => 'Ashgabat','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'TN','name' => 'Africa/Tunis','city' => 'Tunis','offset' => '3600','gmt' => '+01:00','abbreviation' => 'CET' ],
			[ 'country_code' => 'TO','name' => 'Pacific/Tongatapu','city' => 'Tongatapu','offset' => '46800','gmt' => '+13:00','abbreviation' => '+13' ],
			[ 'country_code' => 'TR','name' => 'Europe/Istanbul','city' => 'Istanbul','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'TT','name' => 'America/Port_of_Spain','city' => 'Port of Spain','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'TV','name' => 'Pacific/Funafuti','city' => 'Funafuti','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'TW','name' => 'Asia/Taipei','city' => 'Taipei','offset' => '28800','gmt' => '+08:00','abbreviation' => 'CST' ],
			[ 'country_code' => 'TZ','name' => 'Africa/Dar_es_Salaam','city' => 'Dar es Salaam','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'UA','name' => 'Europe/Kiev','city' => 'Kiev','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'UA','name' => 'Europe/Uzhgorod','city' => 'Uzhgorod','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'UA','name' => 'Europe/Zaporozhye','city' => 'Zaporozhye','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EEST' ],
			[ 'country_code' => 'UG','name' => 'Africa/Kampala','city' => 'Kampala','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'UM','name' => 'Pacific/Midway','city' => 'Midway','offset' => '-39600','gmt' => '-11:00','abbreviation' => 'SST' ],
			[ 'country_code' => 'UM','name' => 'Pacific/Wake','city' => 'Wake','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'US','name' => 'America/New_York','city' => 'New York','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Detroit','city' => 'Detroit','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Kentucky/Louisville','city' => 'Louisville','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Kentucky/Monticello','city' => 'Monticello','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Indianapolis','city' => 'Indianapolis','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Vincennes','city' => 'Vincennes','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Winamac','city' => 'Winamac','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Marengo','city' => 'Marengo','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Petersburg','city' => 'Petersburg','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Vevay','city' => 'Vevay','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'EDT' ],
			[ 'country_code' => 'US','name' => 'America/Chicago','city' => 'Chicago','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Tell_City','city' => 'Tell City','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/Indiana/Knox','city' => 'Knox','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/Menominee','city' => 'Menominee','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/North_Dakota/Center','city' => 'Center','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/North_Dakota/New_Salem','city' => 'New Salem','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/North_Dakota/Beulah','city' => 'Beulah','offset' => '-18000','gmt' => '-05:00','abbreviation' => 'CDT' ],
			[ 'country_code' => 'US','name' => 'America/Denver','city' => 'Denver','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'US','name' => 'America/Boise','city' => 'Boise','offset' => '-21600','gmt' => '-06:00','abbreviation' => 'MDT' ],
			[ 'country_code' => 'US','name' => 'America/Phoenix','city' => 'Phoenix','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'MST' ],
			[ 'country_code' => 'US','name' => 'America/Los_Angeles','city' => 'Los Angeles','offset' => '-25200','gmt' => '-07:00','abbreviation' => 'PDT' ],
			[ 'country_code' => 'US','name' => 'America/Anchorage','city' => 'Anchorage','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Juneau','city' => 'Juneau','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Sitka','city' => 'Sitka','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Metlakatla','city' => 'Metlakatla','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Yakutat','city' => 'Yakutat','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Nome','city' => 'Nome','offset' => '-28800','gmt' => '-08:00','abbreviation' => 'AKDT' ],
			[ 'country_code' => 'US','name' => 'America/Adak','city' => 'Adak','offset' => '-32400','gmt' => '-09:00','abbreviation' => 'HDT' ],
			[ 'country_code' => 'US','name' => 'Pacific/Honolulu','city' => 'Honolulu','offset' => '-36000','gmt' => '-10:00','abbreviation' => 'HST' ],
			[ 'country_code' => 'UY','name' => 'America/Montevideo','city' => 'Montevideo','offset' => '-10800','gmt' => '-03:00','abbreviation' => '-03' ],
			[ 'country_code' => 'UZ','name' => 'Asia/Samarkand','city' => 'Samarkand','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'UZ','name' => 'Asia/Tashkent','city' => 'Tashkent','offset' => '18000','gmt' => '+05:00','abbreviation' => '+05' ],
			[ 'country_code' => 'VA','name' => 'Europe/Vatican','city' => 'Vatican','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CEST' ],
			[ 'country_code' => 'VC','name' => 'America/St_Vincent','city' => 'St Vincent','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'VE','name' => 'America/Caracas','city' => 'Caracas','offset' => '-14400','gmt' => '-04:00','abbreviation' => '-04' ],
			[ 'country_code' => 'VG','name' => 'America/Tortola','city' => 'Tortola','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'VI','name' => 'America/St_Thomas','city' => 'St Thomas','offset' => '-14400','gmt' => '-04:00','abbreviation' => 'AST' ],
			[ 'country_code' => 'VN','name' => 'Asia/Ho_Chi_Minh','city' => 'Ho Chi Minh','offset' => '25200','gmt' => '+07:00','abbreviation' => '+07' ],
			[ 'country_code' => 'VU','name' => 'Pacific/Efate','city' => 'Efate','offset' => '39600','gmt' => '+11:00','abbreviation' => '+11' ],
			[ 'country_code' => 'WF','name' => 'Pacific/Wallis','city' => 'Wallis','offset' => '43200','gmt' => '+12:00','abbreviation' => '+12' ],
			[ 'country_code' => 'WS','name' => 'Pacific/Apia','city' => 'Apia','offset' => '50400','gmt' => '+14:00','abbreviation' => '+14' ],
			[ 'country_code' => 'YE','name' => 'Asia/Aden','city' => 'Aden','offset' => '10800','gmt' => '+03:00','abbreviation' => '+03' ],
			[ 'country_code' => 'YT','name' => 'Indian/Mayotte','city' => 'Mayotte','offset' => '10800','gmt' => '+03:00','abbreviation' => 'EAT' ],
			[ 'country_code' => 'ZA','name' => 'Africa/Johannesburg','city' => 'Johannesburg','offset' => '7200','gmt' => '+02:00','abbreviation' => 'SAST' ],
			[ 'country_code' => 'ZM','name' => 'Africa/Lusaka','city' => 'Lusaka','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ],
			[ 'country_code' => 'ZW','name' => 'Africa/Harare','city' => 'Harare','offset' => '7200','gmt' => '+02:00','abbreviation' => 'CAT' ]
		];

		foreach ($data as $row) {
			Timezone::firstOrCreate(
				['name' => $row['name']], 
				$row
			);
        }
    }
}
